Parse file using Pandas library function and write output to csv file.

In [1]:
# importing pandas library

import pandas as pd

In [2]:
# reading json file using pandas

df = pd.read_json('sample_output.json')

# printing the contents of the json file

df

,ip_from,ip_to,country_code,country,region,city,latitude,longitude,zip_code,time_zone,...,weather_station_name,mcc,mnc,mobile_brand,elevation,ip_from_inet,ip_to_inet,ip_count,cidr,insert_ts
0,16777216,16777471,US,United States of America,California,San Jose,37.339390,-121.89496,95101,-07:00,...,San Jose,-,-,-,24,1.0.0.0,1.0.0.255,256,{1.0.0.0/24},2023-01-08
1,16777472,16778239,CN,China,Fujian,Fuzhou,26.061390,119.30611,350004,+08:00,...,Fuzhou,460,03/11,China Telecom,4,1.0.1.0,1.0.3.255,768,"{1.0.1.0/24,1.0.2.0/23}",2023-02-19
2,16778240,16778495,AU,Australia,Tasmania,Glebe,-42.874638,147.32806,7000,+10:00,...,Hobart,-,-,-,47,1.0.4.0,1.0.4.255,256,{1.0.4.0/24},2023-01-05
3,16778496,16779263,AU,Australia,Victoria,Melbourne,-37.814007,144.96317,3000,+10:00,...,Melbourne,-,-,-,13,1.0.5.0,1.0.7.255,768,"{1.0.5.0/24,1.0.6.0/23}",2023-02-10
4,16779264,16781311,CN,China,Guangdong,Guangzhou,23.127361,113.26457,510140,+08:00,...,Guangzhou,460,03/11,China Telecom,11,1.0.8.0,1.0.15.255,2048,{1.0.8.0/21},2023-01-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,18989944,18989951,JP,Japan,Tokyo,Tokyo,35.689500,139.69232,214-0021,+09:00,...,Tokyo,-,-,-,37,1.33.195.120,1.33.195.127,8,{1.33.195.120/29},2023-02-17
1995,18989952,18990079,JP,Japan,Osaka,Osaka,34.694218,135.50223,541-0041,+09:00,...,Osaka,440,10,freetel,4,1.33.195.128,1.33.195.255,128,{1.33.195.128/25},2023-01-05
1996,18990080,18990087,JP,Japan,Tokyo,Tokyo,35.689500,139.69232,105-0003,+09:00,...,Tokyo,-,-,-,37,1.33.196.0,1.33.196.7,8,{1.33.196.0/29},2023-02-09
1997,18990088,18990095,JP,Japan,Hiroshima,Hiroshima,34.385868,132.45543,730-0011,+09:00,...,Hiroshima,-,-,-,13,1.33.196.8,1.33.196.15,8,{1.33.196.8/29},2023-01-26
1998,18990096,18990103,JP,Japan,Tokyo,Tokyo,35.689500,139.69232,105-0003,+09:00,...,Tokyo,-,-,-,37,1.33.196.16,1.33.196.23,8,{1.33.196.16/29},2023-02-19

In [3]:
# converting DataFrame to csv file

df.to_csv('assignment2.csv', index = False)

Parse file using json,csv python library and write output to csv file.

In [5]:
# importing json and csv library

import json
import csv

# opening the JSON file
with open('sample_output.json') as f:
    data = json.load(f)

# creating a CSV writer object
csv_writer = csv.writer(open('assignment_2.csv', 'w'))

# writing the header row
csv_writer.writerow(data[0].keys())

# writing the data rows
for row in data:
    csv_writer.writerow(row.values())